# Generated by Django 5.0.4 on 2024-05-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_productcolor_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcolor",
            name="title",
            field=models.CharField(default="blue", max_length=20),
            preserve_default=False,
        ),
    ]
