# Generated by Django 5.0.4 on 2024-05-04 14:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productcolor_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolor",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
