# Generated by Django 4.2.1 on 2024-05-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("image", models.ImageField(upload_to="blog_posts")),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "posts",
            },
        ),
    ]
