# Generated by Django 4.2.1 on 2024-05-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LookBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
            ],
            options={
                "db_table": "lookbooks",
            },
        ),
        migrations.CreateModel(
            name="LookBookImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="lookbooks")),
                (
                    "lookbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lookbooks.lookbook",
                    ),
                ),
            ],
            options={
                "db_table": "lookbook_images",
            },
        ),
    ]
